// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.yuklore.spendflux

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Status data returned by [FluxAiHostApi.getModelStatus].
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class FluxAiModelStatus (
  val isLoaded: Boolean,
  val modelPath: String? = null,
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FluxAiModelStatus {
      val isLoaded = pigeonVar_list[0] as Boolean
      val modelPath = pigeonVar_list[1] as String?
      val errorMessage = pigeonVar_list[2] as String?
      return FluxAiModelStatus(isLoaded, modelPath, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isLoaded,
      modelPath,
      errorMessage,
    )
  }
}

/**
 * Result returned by [FluxAiHostApi.getAssetPackModelPath].
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AssetPackStatus (
  /** True when the asset pack is installed and the model file is accessible. */
  val isAvailable: Boolean,
  /** Absolute path to the model file inside the asset pack, or null. */
  val modelPath: String? = null,
  /** Human-readable error when [isAvailable] is false. */
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AssetPackStatus {
      val isAvailable = pigeonVar_list[0] as Boolean
      val modelPath = pigeonVar_list[1] as String?
      val errorMessage = pigeonVar_list[2] as String?
      return AssetPackStatus(isAvailable, modelPath, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isAvailable,
      modelPath,
      errorMessage,
    )
  }
}
private open class FluxAiApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FluxAiModelStatus.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AssetPackStatus.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is FluxAiModelStatus -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is AssetPackStatus -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Dart → Android: host-side API for LLM inference operations.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface FluxAiHostApi {
  /**
   * Returns the absolute path to the Gemma model inside the Play Asset
   * Delivery pack ("model_delivery"), or an error message if the pack is not
   * yet installed.
   */
  fun getAssetPackModelPath(callback: (Result<AssetPackStatus>) -> Unit)
  /** Loads the Gemma model from [modelPath]. Returns true on success. */
  fun loadModel(modelPath: String, callback: (Result<Boolean>) -> Unit)
  /** Unloads the active model and releases native resources. */
  fun unloadModel(callback: (Result<Unit>) -> Unit)
  /** Returns the current model load status. */
  fun getModelStatus(callback: (Result<FluxAiModelStatus>) -> Unit)
  /**
   * Generates a full (non-streaming) response synchronously.
   * Prefer [generateResponseStreaming] for interactive chat.
   */
  fun generateResponse(prompt: String, systemPrompt: String, callback: (Result<String>) -> Unit)
  /**
   * Begins streaming generation. Tokens arrive via [FluxAiFlutterApi.onToken].
   * Returns true if generation was started successfully.
   */
  fun generateResponseStreaming(prompt: String, systemPrompt: String, callback: (Result<Boolean>) -> Unit)
  /** Cancels any in-progress generation immediately. */
  fun cancelGeneration()

  companion object {
    /** The codec used by FluxAiHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      FluxAiApiPigeonCodec()
    }
    /** Sets up an instance of `FluxAiHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: FluxAiHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.spend_sense.FluxAiHostApi.getAssetPackModelPath$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getAssetPackModelPath{ result: Result<AssetPackStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.spend_sense.FluxAiHostApi.loadModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modelPathArg = args[0] as String
            api.loadModel(modelPathArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.spend_sense.FluxAiHostApi.unloadModel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.unloadModel{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.spend_sense.FluxAiHostApi.getModelStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getModelStatus{ result: Result<FluxAiModelStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.spend_sense.FluxAiHostApi.generateResponse$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val promptArg = args[0] as String
            val systemPromptArg = args[1] as String
            api.generateResponse(promptArg, systemPromptArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.spend_sense.FluxAiHostApi.generateResponseStreaming$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val promptArg = args[0] as String
            val systemPromptArg = args[1] as String
            api.generateResponseStreaming(promptArg, systemPromptArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.spend_sense.FluxAiHostApi.cancelGeneration$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.cancelGeneration()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Android → Dart: Flutter-side callbacks from the native LLM layer.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class FluxAiFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by FluxAiFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      FluxAiApiPigeonCodec()
    }
  }
  /** Called for each token emitted during streaming generation. */
  fun onToken(tokenArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.spend_sense.FluxAiFlutterApi.onToken$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(tokenArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Called when streaming generation completes with the full response text. */
  fun onGenerationComplete(fullResponseArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.spend_sense.FluxAiFlutterApi.onGenerationComplete$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(fullResponseArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Called when the native layer encounters an error during inference. */
  fun onGenerationError(messageArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.spend_sense.FluxAiFlutterApi.onGenerationError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
